// LinearAerospikeContour.cs — Sprint 26 (2026-04-23):
// Linear (extruded-rectangular) aerospike plug contour generator.
//
// Relation to AerospikeContour
// ────────────────────────────
// The underlying Angelino 2D parametric curve is identical for both
// topologies — Prandtl-Meyer turning from M=1 at the throat to M_exit
// at the plug tip. What differs is how the 2D curve becomes a 3D body:
//
//   • Axisymmetric (classic, Sprints 1-15): revolve the curve around
//     the +X axis. Plug cross-section is a circle of radius
//     R_inner_mm at every station; wetted surface is 2π · r · dx.
//
//   • Linear (this file, Sprint 26): extrude the curve along the
//     transverse axis (+Z, say). Plug cross-section is a rectangle of
//     dimensions (2·R_inner_mm) × PlugWidth_mm at every station;
//     flow exits along TWO longitudinal slots, one above and one
//     below the plug. Wetted surface per station is 2 · PlugWidth · dx
//     (top + bottom faces). This is the XRS-2200 / X-33 lineage.
//
// Throat-area accounting
// ──────────────────────
// Classic aerospike throat area = π(R_o² − R_i²). Linear aerospike
// throat area = 2 · h_throat · PlugWidth_mm — two rectangular slots of
// height equal to the plug-tip half-height, each PlugWidth_mm long
// in the transverse direction. The factor of 2 captures the symmetric
// top+bottom slots; single-sided variants are not in scope for
// Sprint 26.
//
// What gets reused
// ────────────────
// Every consumer of AerospikeContour downstream is blind to the
// linear/axisymmetric distinction unless it opts in by reading the
// new IsLinear flag. The thermal solver, voxel builder, and
// feasibility evaluator each do exactly one branch on that flag and
// otherwise run the same code — so the maintenance cost of this
// sibling topology is additive per Sprint 21's "no switch hunt"
// forcing function.

using Voxelforge.Chamber;

namespace Voxelforge.Chamber;

/// <summary>
/// Sprint 26 (2026-04-23): parametric linear-aerospike plug contour
/// generator. Shares the Angelino 2D curve math with
/// <see cref="AerospikeContourGenerator"/>; differs only in how the
/// resulting contour is interpreted downstream (rectangular extrusion
/// vs axisymmetric revolve) — signalled by the
/// <see cref="AerospikeContour.IsLinear"/> flag on the returned record.
/// </summary>
public static class LinearAerospikeContourGenerator
{
    /// <summary>Minimum aspect ratio (plug length / plug width) the
    /// Angelino model remains physically meaningful for — below this
    /// the side-wall recirculation bubble covers more than half the
    /// expansion surface (X-33 XRS-2200 test-campaign floor).</summary>
    public const double MinAspectRatio = 0.30;

    /// <summary>Maximum aspect ratio before the plug becomes a
    /// long-span cantilever whose thermal-bending stiffness can't be
    /// managed at LPBF scale with the shipped wall material library.</summary>
    public const double MaxAspectRatio = 5.00;

    /// <summary>
    /// Build a linear-aerospike contour. The 2D Angelino curve is
    /// generated by the existing <see cref="AerospikeContourGenerator.Generate"/>
    /// (the math is topology-agnostic); this wrapper stamps the linear-
    /// specific metadata — PlugWidth_mm, LinearAspectRatio, IsLinear —
    /// and overrides ThroatAnnulusArea_mm2 to the rectangular slot
    /// total.
    /// </summary>
    /// <param name="throatHeight_mm">Plug-tip half-height (mm) at the
    ///     throat. Equivalent role to ThroatOuterRadius_mm on the
    ///     axisymmetric path; the 2D Angelino curve is identical.</param>
    /// <param name="plugWidth_mm">Transverse extrusion width (mm) of
    ///     the rectangular plug. Paired with <paramref name="throatHeight_mm"/>
    ///     to drive throat area, wetted surface, and the aspect-ratio
    ///     feasibility gate.</param>
    /// <param name="expansionRatio">A_e / A_t on the truncated-plug base.</param>
    /// <param name="plugLengthRatio">Truncation fraction (0.15 – 1.0).</param>
    /// <param name="gamma">Specific-heat ratio of the chamber gas.</param>
    /// <param name="stationCount">Axial-station count along the plug.</param>
    /// <param name="includeCowl">Short outer cowl around the throat.</param>
    /// <param name="contourRadius_mm">Override for the Angelino R_o used to
    ///     derive plug full length. When non-zero, this value is passed as
    ///     <c>throatOuterRadius_mm</c> to <see cref="AerospikeContourGenerator.Generate"/>
    ///     instead of <paramref name="throatHeight_mm"/>. For wide-plug engines
    ///     where the plug width greatly exceeds the slot height (XRS-2200:
    ///     W ≈ 2 300 mm vs h_throat ≈ 34 mm), the exit-equivalent radius
    ///     <c>√(ε·A_t/π)</c> recovers the correct plug length. Leave as 0
    ///     (default) to use <paramref name="throatHeight_mm"/> as R_o.</param>
    public static AerospikeContour Generate(
        double throatHeight_mm,
        double plugWidth_mm,
        double expansionRatio,
        double plugLengthRatio = 0.30,
        double gamma = 1.15,
        int stationCount = 80,
        bool includeCowl = true,
        double contourRadius_mm = 0.0)
    {
        if (plugWidth_mm <= 0)
            throw new System.ArgumentOutOfRangeException(nameof(plugWidth_mm),
                "plug transverse width must be positive");

        // For wide-plug linear aerospikes (XRS-2200: W >> h_throat), using
        // h_throat as the Angelino R_o gives L_trunc << real plug length.
        // When contourRadius_mm is supplied, use it as R_o for the
        // L_full = R_o / tan(μ_exit) formula; h_throat still drives the
        // physical slot area (overridden in the `with` block below).
        double r_angelino = contourRadius_mm > 0.0 ? contourRadius_mm : throatHeight_mm;

        var axi = AerospikeContourGenerator.Generate(
            throatOuterRadius_mm: r_angelino,
            expansionRatio:       expansionRatio,
            plugLengthRatio:      plugLengthRatio,
            gamma:                gamma,
            stationCount:         stationCount,
            includeCowl:          includeCowl);

        // Override every field that depends on R_o with physical linear
        // values so downstream consumers (thermal solver, feasibility
        // evaluator, voxel builder) see the correct h_throat-based geometry.
        double throatSlotArea_mm2 = 2.0 * throatHeight_mm * plugWidth_mm;

        // Exit area on the truncated-plug base: rectangle of
        // (2·plug-base-half-height) × PlugWidth_mm. PlugBaseRadius_mm from
        // the axisymmetric generator reflects the r_angelino scale; this is
        // used only for ExitArea / ExpansionRatio on the contour record.
        double exitArea_mm2 = 2.0 * axi.PlugBaseRadius_mm * plugWidth_mm;

        double aspect = axi.PlugTruncatedLength_mm / plugWidth_mm;

        return axi with
        {
            ThroatAnnulusArea_mm2 = throatSlotArea_mm2,
            ThroatOuterRadius_mm  = throatHeight_mm,
            ThroatInnerRadius_mm  = 0.0,
            ExitArea_mm2          = exitArea_mm2,
            ExpansionRatio        = exitArea_mm2 / System.Math.Max(throatSlotArea_mm2, 1e-9),
            CowlLength_mm         = includeCowl ? 0.25 * throatHeight_mm : 0.0,
            CowlOuterRadius_mm    = includeCowl ? throatHeight_mm + 2.0 : 0.0,
            IsLinear              = true,
            PlugWidth_mm          = plugWidth_mm,
            LinearAspectRatio     = aspect,
        };
    }
}
