// PortGeometry.cs — Threaded fluid port boss generator.
//
// Ported from HeatExchangerDesigner/PortGeometry.cs with the HX-specific
// namespace swapped for Voxelforge. Produces external (male)
// threaded nipples for coolant inlets/outlets and sensor taps so the printed
// chamber mates directly with off-the-shelf plumbing fittings (G/BSPP, NPT,
// SAE ORB).
//
// Parallel thread geometry is exact; NPT taper is generated by linearly
// expanding the helix radius with axial distance.
//
// Construction strategy (identical to HX port code, which has been flight-
// tested on printed parts):
//
//   1a. Shoulder collar  : BossDia/2 cylinder that spans the jacket wall and
//                          protrudes a small overhang past the jacket exterior.
//                          Provides a watertight union and a machinist-style
//                          shoulder at the base of the threads.
//
//   1b. Thread shaft     : A frustum (= cylinder when taper = 0) whose surface
//                          matches the helical thread crest at every z — so the
//                          helical cutter straddles the surface and produces a
//                          proper external thread with constant depth. For NPT
//                          the radius SHRINKS with axial distance at
//                          TaperPerSide = 1/32 mm/mm.
//
//   2.  Through-bore     : radius = NominalBore/2, runs end-to-end through the
//                          boss and extends past the back face so the caller
//                          can cut through the jacket to reach the plenum.
//
//   3.  Helical groove   : lattice of short cylindrical cutter beams swept
//                          along the helix path (0.5·pitch radius → V-thread
//                          approximation with ~0.6·pitch depth). The cutter
//                          runs from -1·pitch (lead-in) to +0.5·pitch past the
//                          thread end (lead-out) so the thread terminates
//                          cleanly at both ends.
//
// Why a lattice-of-beams (not a custom analytic helical distance function):
// the lattice/beam sweep is well-tested in PicoGK and gives a continuous
// watertight volume at 0.25–0.5 mm voxel resolutions. A custom analytic helix
// SDF is tractable but easy to get wrong at the lead-in / run-out; the beam
// chain naturally creates proper end caps.
//
// Voxel resolution: at 0.4 mm voxel size, threads below G 1/4 (pitch 1.337
// mm, depth 0.80 mm) start to alias. Smaller ports should fall back to Plain.

using System.Numerics;
using PicoGK;

namespace Voxelforge.Geometry;

/// <summary>
/// Stateless threaded-port geometry builder. Must be called on the PicoGK
/// task thread (voxel operations).
/// </summary>
public static class PortGeometry
{
    /// <summary>
    /// The two voxel objects a caller needs to integrate a threaded port.
    /// <see cref="BossAdd"/> is unioned with the jacket (adds the external
    /// threaded nipple). <see cref="BoreSubtract"/> is subtracted from the
    /// jacket to open the fluid path through the jacket wall behind the boss.
    /// </summary>
    public readonly struct PortBuild
    {
        public Voxels BossAdd      { get; init; }
        public Voxels BoreSubtract { get; init; }
    }

    /// <summary>
    /// Build a threaded port boss at a given face location.
    /// </summary>
    /// <param name="bounds">Global render bounds (shared with other ops).</param>
    /// <param name="spec">Port standard dimensions.</param>
    /// <param name="faceCenter">Centre of the port face on the jacket exterior.</param>
    /// <param name="outward">Unit vector pointing AWAY from the chamber body.</param>
    /// <param name="backPenetrationMM">
    /// How far the boss extends INTO the jacket past <paramref name="faceCenter"/>
    /// — at least jacket thickness so the union is watertight.
    /// </param>
    /// <param name="frontExtensionMM">
    /// How far the nipple extends outward — usually ≈ spec.ThreadLengthMM + lead-in.
    /// </param>
    public static PortBuild Build(
        BBox3 bounds,
        PortSpec spec,
        Vector3 faceCenter,
        Vector3 outward,
        float backPenetrationMM,
        float frontExtensionMM)
    {
        var axis = Vector3.Normalize(outward);

        float halfLen = spec.ThreadLengthMM * 0.5f;
        float taperRate = spec.TaperPerSide;

        // ── 1a. Shoulder collar (BossDia cylinder spanning the jacket wall) ──
        const float collarOverhang = 0.3f;
        var collarStart = faceCenter - axis * backPenetrationMM;
        float collarLen = backPenetrationMM + collarOverhang;
        var collarImpl = new CylinderImplicit(
            collarStart, axis, spec.BossDiaMM / 2f, collarLen);
        var boss = LibraryScope.MakeVoxels(collarImpl, bounds);

        // ── 1b. Thread shaft — frustum matching the helical crest at every z ──
        const float shaftBackOverlap = 0.4f;

        float rAtBase = spec.MajorDiaMM / 2f
                      + (halfLen + shaftBackOverlap) * taperRate;
        float rAtThreadEnd = spec.MajorDiaMM / 2f
                           + (halfLen - spec.ThreadLengthMM) * taperRate;

        // Nose radius: slightly below minor diameter, but always ≥ bore + 0.8 mm.
        float rNose = MathF.Max(
            spec.MinorDiaMM / 2f - 0.15f * spec.PitchMM,
            spec.NominalBoreMM / 2f + 0.8f);
        rNose = MathF.Min(rNose, rAtThreadEnd - 0.2f);
        if (rNose < 0.5f) rNose = 0.5f;

        float chamferLen = spec.PitchMM;
        float mainEndZ = spec.ThreadLengthMM;
        float chamferEndZ = MathF.Max(mainEndZ + chamferLen, frontExtensionMM);

        var shaftLattice = new Lattice();
        shaftLattice.AddBeam(
            faceCenter - axis * shaftBackOverlap, rAtBase,
            faceCenter + axis * mainEndZ, rAtThreadEnd,
            false);
        shaftLattice.AddBeam(
            faceCenter + axis * mainEndZ, rAtThreadEnd,
            faceCenter + axis * chamferEndZ, rNose,
            false);
        boss.BoolAdd(new Voxels(shaftLattice));

        // ── 2. Through-bore (and usable as shell cut-through) ──
        float boreBack = backPenetrationMM * 1.5f + 2f;
        var boreStart = faceCenter - axis * boreBack;
        float boreLen = boreBack + frontExtensionMM + 2f;
        var boreImpl = new CylinderImplicit(
            boreStart, axis, spec.NominalBoreMM / 2f, boreLen);
        var bore = LibraryScope.MakeVoxels(boreImpl, bounds);
        boss.BoolSubtract(bore);

        // ── 3. Helical thread groove ──
        if (spec.PitchMM > 0.01f && spec.ThreadLengthMM > 0.5f)
        {
            var grooves = BuildHelicalGroove(spec, faceCenter, axis);
            if (grooves != null) boss.BoolSubtract(grooves);
        }

        return new PortBuild { BossAdd = boss, BoreSubtract = bore };
    }

    /// <summary>
    /// Helical thread groove as a lattice of short cylindrical cutter segments
    /// swept along the helix path. Returns null for degenerate threads.
    /// </summary>
    private static Voxels? BuildHelicalGroove(
        PortSpec spec, Vector3 faceCenter, Vector3 axis)
    {
        float pitch = spec.PitchMM;
        float threadLen = spec.ThreadLengthMM;
        float halfLen = threadLen * 0.5f;

        float cutterR = 0.5f * pitch;
        float leadIn = 1.0f * pitch;
        float leadOut = 0.5f * pitch;

        // Orthonormal basis (u, v) perpendicular to the port axis.
        Vector3 refVec = MathF.Abs(axis.Y) < 0.9f ? Vector3.UnitY : Vector3.UnitX;
        var u = Vector3.Normalize(Vector3.Cross(axis, refVec));
        var v = Vector3.Cross(axis, u);

        const int segPerTurn = 36;
        int numTurns = (int)MathF.Ceiling(threadLen / pitch) + 2;
        int totalSegs = numTurns * segPerTurn;
        float dz = pitch / segPerTurn;
        float zStart = -leadIn;
        float zEnd = threadLen + leadOut;

        float taperRate = spec.TaperPerSide;
        float crestAtMid = spec.MajorDiaMM * 0.5f;

        var lattice = new Lattice();
        Vector3? prev = null;
        bool anyBeam = false;

        for (int i = 0; i <= totalSegs; i++)
        {
            float z = zStart + i * dz;
            if (z > zEnd) break;

            float theta = 2f * MathF.PI * z / pitch;
            float crest = crestAtMid + (halfLen - z) * taperRate;

            Vector3 p = faceCenter
                      + axis * z
                      + u * (crest * MathF.Cos(theta))
                      + v * (crest * MathF.Sin(theta));

            if (prev.HasValue)
            {
                lattice.AddBeam(prev.Value, cutterR, p, cutterR, false);
                anyBeam = true;
            }
            prev = p;
        }

        return anyBeam ? new Voxels(lattice) : null;
    }

    /// <summary>
    /// Recommended axial clearance for a threaded port, for extending render
    /// bounds so the boss and its helical groove aren't clipped.
    /// </summary>
    public static float RequiredClearanceMM(PortSpec spec, float backPenetrationMM)
    {
        if (spec.Standard == PortStandard.Plain) return 0f;
        return backPenetrationMM + spec.ThreadLengthMM + 2f * spec.PitchMM + 2f;
    }
}
